### ISSUE TITLE
Get bank details

### ISSUE THREAD

**Issue by Antonio12345Nunez** [Antonio12345Nunez/GESPRO_Practica_2_Curso_2024_2025#18]
As a user, I want to view my bank details, so that I can manage my account information and ensure everything is up to date.

Description:

Display key account details such as account number, branch information, and routing number.
Provide options to update personal details, contact information, and linked accounts.
Images:
Example of the account details page with key information shown.

Links:
Link to bank policies regarding account information and security.

Other resources:
Security tips for protecting bank account details.

Acceptance Criteria:

Users can easily access their account details from the settings or profile section.
All account information is displayed clearly and accurately.
Sensitive information is protected with security measures like encryption or authentication.
Users can request updates to their details securely, with confirmation upon successful change.

**Comment by NicolasVO-dot** [comment]
Termino yo las ultimas tareas de la Release 1 y me pongo con la dos
